// Members data with optimized structure for database compatibility
export const MEMBERS = [
    {
        id: 'yuval-avidani',
        username: 'yuval-avidani',
        password: '1234',
        name_he: 'יובל אבידני',
        name_en: 'Yuval Avidani',
        role_he: 'מומחה בבינה מלאכותית, עושה עבור משרד האוצר וקבוצת שטראוס',
        role_en: 'AI Expert, working for Treasury Ministry and Strauss Group',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/yuval-avidani.jpg',
        skills: ['AI Strategy', 'Machine Learning', 'Business Intelligence'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'tsippi-abramovitz',
        username: 'tsippi-abramovitz',
        password: '1234',
        name_he: 'ציפי אברמוביץ',
        name_en: 'Tsippi Abramovitz',
        role_he: 'מורה לחינוך מיוחד, משתמשת בAI בחינוך',
        role_en: 'Special Education Teacher, Using AI in Education',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/tsippi-abramovitz.jpg',
        skills: ['AI in Education', 'Special Education', 'Educational Technology'],
        social_links: {},
        gallery_items: [],
        category: 'ai-education',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'evyatar-edri',
        username: 'evyatar-edri',
        password: '1234',
        name_he: 'אביתר אדרי',
        name_en: 'Evyatar Edri',
        role_he: 'אמן דיגיטלי, מעצב, יזם',
        role_en: 'Digital Artist, Designer, Entrepreneur',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/evyatar-edri.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'eyal-izenman',
        username: 'eyal-izenman',
        password: '1234',
        name_he: 'איל איזנמן',
        name_en: 'Eyal Izenman',
        role_he: 'יוצר חזותי, בינאי ומורה',
        role_en: 'Visual Creator, AI Specialist, and Instructor',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/eyal-izenman.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'shay-halahmi',
        username: 'shay-halahmi',
        password: '1234',
        name_he: 'שי הלחמי',
        name_en: 'Shay Halahmi',
        role_he: 'מעצב גרפי, אמן AI ומורה',
        role_en: 'Graphic Designer, AI Artist and Teacher',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/shay-halahmi.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'ella-uzan',
        username: 'ella-uzan',
        password: '1234',
        name_he: 'אלה אוזן',
        name_en: 'Ella Uzan',
        role_he: 'צלמת, מעצבת ואנימטורית',
        role_en: 'Photographer, Designer, and Animator',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/ella-uzan.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'hagai-onn',
        username: 'hagai-onn',
        password: '1234',
        name_he: 'חגי און',
        name_en: 'Hagai Onn',
        role_he: 'מהנדס מחשבים, מתכנת, אמן AI',
        role_en: 'Computer Engineer, Programmer, AI Artist',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/hagai-onn.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'shelly-or',
        username: 'shelly-or',
        password: '1234',
        name_he: 'שלי אור',
        name_en: 'Shelly Or',
        role_he: 'מומחית לבינה מלאכותית, מרצה לעיצוב ומנהלת סטודיו קניבל',
        role_en: 'AI Expert, Design Lecturer, Cannibal Studio Manager',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/shelly-or.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'maya-elav-nachshon',
        username: 'maya-elav-nachshon',
        password: '1234',
        name_he: 'מאיה אלאב נחשון',
        name_en: 'Maya Elav Nachshon',
        role_he: 'ארט דירקטורית, מאפיינת חווית משתמש ומעצבת ממשקים, אמנית AI',
        role_en: 'Art Director, UX Specialist, Interface Designer, AI Artist',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/maya-elav-nachshon.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'avichai-eliasi',
        username: 'avichai-eliasi',
        password: '1234',
        name_he: 'אביחי אליאסי',
        name_en: 'Avichai Eliasi',
        role_he: 'מרצה ל-AI מנהל שיווק, מוצר ומיתוג ומעצב גרפי',
        role_en: 'AI Lecturer, Marketing, Product, and Branding Manager, Graphic Designer',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/avichai-eliasi.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'tali-appel',
        username: 'tali-appel',
        password: '1234',
        name_he: 'טלי אפל',
        name_en: 'Tali Appel',
        role_he: 'יוצרת אמנות, אנימציה, סרטונים, קליפרים, יועצת פילוסופית',
        role_en: 'Art Creator, Animation, Video, Clipper, Philosophical Consultant',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/tali-appel.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'ori-bejerno',
        username: 'ori-bejerno',
        password: '1234',
        name_he: 'אורי בז׳רנו',
        name_en: 'Ori Bejerno',
        role_he: 'אמן AI, מעצב גרפי ומנהל קריאייטיב',
        role_en: 'AI Artist, Graphic Designer and Creative Director',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/ori-bejerno.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'shachar-golan',
        username: 'shachar-golan',
        password: '1234',
        name_he: 'שחר גולן',
        name_en: 'Shachar Golan',
        role_he: 'אמן AI, מעצב גרפי ומורה',
        role_en: 'AI Artist, Graphic Designer and Teacher',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/shachar-golan.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'michal-levitzky',
        username: 'michal-levitzky',
        password: '1234',
        name_he: 'מיכל לויצקי',
        name_en: 'Michal Levitzky',
        role_he: 'אמנית AI, מעצבת גרפית ומורה',
        role_en: 'AI Artist, Graphic Designer and Teacher',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/michal-levitzky.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'daniel-nehemia',
        username: 'daniel-nehemia',
        password: '1234',
        name_he: 'דניאל נחמיה',
        name_en: 'Daniel Nehemia',
        role_he: 'אמן AI, מעצב גרפי ומורה',
        role_en: 'AI Artist, Graphic Designer and Teacher',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/daniel-nehemia.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'shahar-fleisher',
        username: 'shahar-fleisher',
        password: '1234',
        name_he: 'שחר פליישר',
        name_en: 'Shahar Fleisher',
        role_he: 'אמן AI, מעצב גרפי ומורה',
        role_en: 'AI Artist, Graphic Designer and Teacher',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/shahar-fleisher.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'noa-rabiner',
        username: 'noa-rabiner',
        password: '1234',
        name_he: 'נועה רבינר',
        name_en: 'Noa Rabiner',
        role_he: 'אמנית AI, מעצבת גרפית ומורה',
        role_en: 'AI Artist, Graphic Designer and Teacher',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/noa-rabiner.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'nataly-shafir',
        username: 'nataly-shafir',
        password: '1234',
        name_he: 'נטלי שפיר',
        name_en: 'Nataly Shafir',
        role_he: 'אמנית AI, מעצבת גרפית ומורה',
        role_en: 'AI Artist, Graphic Designer and Teacher',
        bio_he: 'תיאור מלא יבוא בהמשך',
        bio_en: 'Full description to be added',
        image_url: 'assets/nataly-shafir.jpg',
        skills: [],
        social_links: {},
        gallery_items: [],
        courses: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'ron-cohen',
        username: 'ron-cohen',
        password: '1234',
        name_he: 'רון כהן',
        name_en: 'Ron Cohen',
        role_he: 'אמן דיגיטלי ומעצב UX/UI',
        role_en: 'Digital Artist and UX/UI Designer',
        bio_he: 'יוצר תוכן דיגיטלי המשלב AI עם עיצוב מוצר',
        bio_en: 'Digital content creator combining AI with product design',
        image_url: 'assets/default-profile.jpg',
        skills: ['Digital Art', 'UX/UI Design', 'AI Tools'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'maya-stern',
        username: 'maya-stern',
        password: '1234',
        name_he: 'מאיה שטרן',
        name_en: 'Maya Stern',
        role_he: 'מומחית לעיבוד שפה טבעית ובינה מלאכותית',
        role_en: 'NLP and AI Specialist',
        bio_he: 'חוקרת ומפתחת מודלים של עיבוד שפה טבעית',
        bio_en: 'Researcher and developer of NLP models',
        image_url: 'assets/default-profile.jpg',
        skills: ['NLP', 'Machine Learning', 'Python'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'david-levy',
        username: 'david-levy',
        password: '1234',
        name_he: 'דוד לוי',
        name_en: 'David Levy',
        role_he: 'אמן AI ומרצה לאמנות דיגיטלית',
        role_en: 'AI Artist and Digital Art Lecturer',
        bio_he: 'יוצר אמנות גנרטיבית ומלמד טכניקות AI באמנות',
        bio_en: 'Creates generative art and teaches AI techniques in art',
        image_url: 'assets/default-profile.jpg',
        skills: ['Generative Art', 'Teaching', 'Digital Art'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'noa-berkowitz',
        username: 'noa-berkowitz',
        password: '1234',
        name_he: 'נועה ברקוביץ',
        name_en: 'Noa Berkowitz',
        role_he: 'מעצבת גרפית ואמנית AI',
        role_en: 'Graphic Designer and AI Artist',
        bio_he: 'מתמחה בעיצוב ויזואלי בעזרת כלי AI',
        bio_en: 'Specializes in visual design using AI tools',
        image_url: 'assets/default-profile.jpg',
        skills: ['Graphic Design', 'AI Art', 'Visual Design'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'amit-sharon',
        username: 'amit-sharon',
        password: '1234',
        name_he: 'עמית שרון',
        name_en: 'Amit Sharon',
        role_he: 'מפתח תוכנה ומומחה AI',
        role_en: 'Software Developer and AI Expert',
        bio_he: 'מפתח פתרונות AI מותאמים אישית',
        bio_en: 'Develops customized AI solutions',
        image_url: 'assets/default-profile.jpg',
        skills: ['Software Development', 'AI Development', 'Python'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'tamar-klein',
        username: 'tamar-klein',
        password: '1234',
        name_he: 'תמר קליין',
        name_en: 'Tamar Klein',
        role_he: 'אמנית דיגיטלית ומאיירת',
        role_en: 'Digital Artist and Illustrator',
        bio_he: 'יוצרת איורים דיגיטליים בשילוב טכנולוגיות AI',
        bio_en: 'Creates digital illustrations combining AI technologies',
        image_url: 'assets/default-profile.jpg',
        skills: ['Digital Illustration', 'AI Art', 'Character Design'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'gil-marcus',
        username: 'gil-marcus',
        password: '1234',
        name_he: 'גיל מרקוס',
        name_en: 'Gil Marcus',
        role_he: 'מומחה לראייה ממוחשבת ו-AI',
        role_en: 'Computer Vision and AI Expert',
        bio_he: 'מפתח מערכות ראייה ממוחשבת מתקדמות',
        bio_en: 'Develops advanced computer vision systems',
        image_url: 'assets/default-profile.jpg',
        skills: ['Computer Vision', 'Deep Learning', 'Python'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'ruth-avital',
        username: 'ruth-avital',
        password: '1234',
        name_he: 'רות אביטל',
        name_en: 'Ruth Avital',
        role_he: 'אמנית מולטימדיה ומרצה',
        role_en: 'Multimedia Artist and Lecturer',
        bio_he: 'יוצרת אמנות אינטראקטיבית בשילוב AI',
        bio_en: 'Creates interactive art incorporating AI',
        image_url: 'assets/default-profile.jpg',
        skills: ['Multimedia Art', 'Interactive Design', 'Teaching'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'yair-goldman',
        username: 'yair-goldman',
        password: '1234',
        name_he: 'יאיר גולדמן',
        name_en: 'Yair Goldman',
        role_he: 'מומחה לאוטומציה ו-AI',
        role_en: 'Automation and AI Expert',
        bio_he: 'מפתח פתרונות אוטומציה חכמים',
        bio_en: 'Develops smart automation solutions',
        image_url: 'assets/default-profile.jpg',
        skills: ['Automation', 'AI Development', 'Process Optimization'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'dana-weiss',
        username: 'dana-weiss',
        password: '1234',
        name_he: 'דנה וייס',
        name_en: 'Dana Weiss',
        role_he: 'אמנית דיגיטלית ומעצבת תנועה',
        role_en: 'Digital Artist and Motion Designer',
        bio_he: 'יוצרת אנימציות ואפקטים ויזואליים בשילוב AI',
        bio_en: 'Creates animations and visual effects using AI',
        image_url: 'assets/default-profile.jpg',
        skills: ['Motion Design', 'Animation', 'Visual Effects'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'liora-ben-ami',
        username: 'liora-ben-ami',
        password: '1234',
        name_he: 'ליאורה בן עמי',
        name_en: 'Liora Ben Ami',
        role_he: 'אמנית AI ומעצבת חוויית משתמש',
        role_en: 'AI Artist and UX Designer',
        bio_he: 'מתמחה בעיצוב ממשקים אינטואיטיביים בשילוב AI',
        bio_en: 'Specializes in intuitive interface design with AI integration',
        image_url: 'assets/default-profile.jpg',
        skills: ['UX Design', 'AI Art', 'Interface Design'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'tal-mizrachi',
        username: 'tal-mizrachi',
        password: '1234',
        name_he: 'טל מזרחי',
        name_en: 'Tal Mizrachi',
        role_he: 'מומחה למערכות לומדות ו-AI',
        role_en: 'Machine Learning and AI Expert',
        bio_he: 'מפתח אלגוריתמים מתקדמים ללמידת מכונה',
        bio_en: 'Develops advanced machine learning algorithms',
        image_url: 'assets/default-profile.jpg',
        skills: ['Machine Learning', 'Deep Learning', 'Algorithm Design'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'michal-bar',
        username: 'michal-bar',
        password: '1234',
        name_he: 'מיכל בר',
        name_en: 'Michal Bar',
        role_he: 'אמנית דיגיטלית ומאיירת',
        role_en: 'Digital Artist and Illustrator',
        bio_he: 'יוצרת איורים דיגיטליים מרהיבים בשילוב AI',
        bio_en: 'Creates stunning digital illustrations with AI',
        image_url: 'assets/default-profile.jpg',
        skills: ['Digital Illustration', 'Character Design', 'AI Art'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'ido-cohen',
        username: 'ido-cohen',
        password: '1234',
        name_he: 'עידו כהן',
        name_en: 'Ido Cohen',
        role_he: 'מפתח AI ומומחה לעיבוד תמונה',
        role_en: 'AI Developer and Image Processing Expert',
        bio_he: 'מפתח אלגוריתמים לעיבוד תמונה ו-AI',
        bio_en: 'Develops algorithms for image processing and AI',
        image_url: 'assets/default-profile.jpg',
        skills: ['Image Processing', 'Computer Vision', 'Python'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'yael-gross',
        username: 'yael-gross',
        password: '1234',
        name_he: 'יעל גרוס',
        name_en: 'Yael Gross',
        role_he: 'אמנית מדיה חדשה ומרצה',
        role_en: 'New Media Artist and Lecturer',
        bio_he: 'יוצרת אמנות דיגיטלית אינטראקטיבית',
        bio_en: 'Creates interactive digital art',
        image_url: 'assets/default-profile.jpg',
        skills: ['New Media Art', 'Interactive Art', 'Teaching'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'amir-levy',
        username: 'amir-levy',
        password: '1234',
        name_he: 'אמיר לוי',
        name_en: 'Amir Levy',
        role_he: 'מומחה לאוטומציה ורובוטיקה',
        role_en: 'Automation and Robotics Expert',
        bio_he: 'מפתח פתרונות אוטומציה ורובוטיקה חכמה',
        bio_en: 'Develops smart automation and robotics solutions',
        image_url: 'assets/default-profile.jpg',
        skills: ['Robotics', 'Automation', 'AI Development'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'shira-tal',
        username: 'shira-tal',
        password: '1234',
        name_he: 'שירה טל',
        name_en: 'Shira Tal',
        role_he: 'אמנית דיגיטלית ומעצבת גרפית',
        role_en: 'Digital Artist and Graphic Designer',
        bio_he: 'יוצרת עיצובים גרפיים מרהיבים בשילוב AI',
        bio_en: 'Creates stunning graphic designs with AI',
        image_url: 'assets/default-profile.jpg',
        skills: ['Graphic Design', 'Digital Art', 'AI Tools'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'guy-ronen',
        username: 'guy-ronen',
        password: '1234',
        name_he: 'גיא רונן',
        name_en: 'Guy Ronen',
        role_he: 'מומחה לבינה מלאכותית ולמידת מכונה',
        role_en: 'AI and Machine Learning Expert',
        bio_he: 'מפתח מודלים מתקדמים של למידת מכונה',
        bio_en: 'Develops advanced machine learning models',
        image_url: 'assets/default-profile.jpg',
        skills: ['Machine Learning', 'Deep Learning', 'Data Science'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'einat-cohen',
        username: 'einat-cohen',
        password: '1234',
        name_he: 'עינת כהן',
        name_en: 'Einat Cohen',
        role_he: 'אמנית AI ומעצבת אינטראקציה',
        role_en: 'AI Artist and Interaction Designer',
        bio_he: 'יוצרת חוויות אינטראקטיביות בשילוב AI',
        bio_en: 'Creates interactive experiences with AI',
        image_url: 'assets/default-profile.jpg',
        skills: ['Interaction Design', 'AI Art', 'UX Design'],
        social_links: {},
        gallery_items: [],
        category: 'digital-artists',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'roee-adam',
        username: 'roee-adam',
        password: '1234',
        name_he: 'רועי אדם',
        name_en: 'Roee Adam',
        role_he: 'מומחה לעיבוד שפה טבעית',
        role_en: 'Natural Language Processing Expert',
        bio_he: 'מפתח מודלים מתקדמים לעיבוד שפה',
        bio_en: 'Develops advanced language processing models',
        image_url: 'assets/default-profile.jpg',
        skills: ['NLP', 'Machine Learning', 'Python'],
        social_links: {},
        gallery_items: [],
        category: 'ai-experts',
        is_admin: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// Updated utility functions for the new structure
export const Utils = {
    getLangText(member, field, lang = 'he') {
        return member[`${field}_${lang}`] || '';
    },

    initializeMembers() {
        window.DATA = window.DATA || {};
        window.DATA.members = MEMBERS;
    },

    createMemberCard(member) {
        return `
            <div class="member-card" data-member-id="${member.id}">
                <img src="${member.image_url}" alt="${member.name_en}" class="member-image">
                <div class="member-info">
                    <h3>
                        <span data-lang="he">${member.name_he}</span>
                        <span data-lang="en" style="display:none;">${member.name_en}</span>
                    </h3>
                    <p class="member-role">
                        <span data-lang="he">${member.role_he}</span>
                        <span data-lang="en" style="display:none;">${member.role_en}</span>
                    </p>
                </div>
            </div>
        `;
    }
};
